import { afterEach, describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { WorkbenchStore } from './store';
const stores: WorkbenchStore[] = [];
afterEach(() => stores.splice(0).forEach(store => { store.close(); fs.rmSync(store.dataDir, { recursive: true, force: true }); }));
describe('one context collector for export and evidence', () => {
  it('includes direct sample Data and dictionaries, avoids recursively expanding referenced samples, and freezes every actual version', () => {
    const store = new WorkbenchStore({ dataDir: fs.mkdtempSync(path.join(os.tmpdir(), 'swb-context-')) }); stores.push(store);
    const object = store.createObject({ canonicalName: '水', role: 'material' });
    const other = store.createSample({ code: 'OTHER', body: '- 不应被展开的其他样品正文\n  - [数据] 私有数据' });
    const sample = store.createSample({ code: 'DIRECT', body: '- [水] 参照 [OTHER]\n  - [水]｜添加量：5 g\n  - [数据] FTIR\n    - 模拟光谱' });
    store.finalizeDocument(other.id); store.finalizeDocument(sample.id);
    const data = store.listData().find(item => item.name === 'FTIR')!;
    const file = store.saveAttachment(Buffer.from('csv-bytes'), 'FTIR.csv', 'text/csv');
    const changedData = store.updateData(data.id, { componentIds: [file.id], expectedVersion: data.version });
    const analysis = store.createAnalysis({ title: '分析', question: '问题正文', body: '- 分析正文', itemIds: [sample.id, data.id, sample.id] });
    const bundle = store.exportContext('analysis', analysis.id);
    expect(bundle.context).toContain('模拟光谱'); expect(bundle.context).toContain('问题正文');
    expect(bundle.context).not.toContain('不应被展开'); expect(bundle.context).not.toContain('私有数据');
    expect(bundle.manifest.entities.filter(entity => entity.id === data.id)).toHaveLength(1);
    expect(bundle.manifest.entities.find(entity => entity.id === data.id)?.version).toBe(changedData.version);
    expect(bundle.manifest.entities.find(entity => entity.id === object.id)?.version).toBe(object.version);
    expect(bundle.manifest.entities.some(entity => entity.type === 'properties')).toBe(true);
    expect(bundle.manifest.host.version).toBe(analysis.version);
    expect(bundle.manifest.attachments[0].sha256).toBe(file.sha256);
    const claim = store.createClaim({ hostType: 'analysis', hostId: analysis.id, text: '有待验证' });
    expect(claim.evidence[0].manifest).toEqual(bundle.manifest);
    expect(claim.evidence[0].content).toBe(bundle.context);
    expect(claim.evidence[0].documents).toEqual(bundle.documents);
    store.updateData(data.id, { body: '- 后来的数据', expectedVersion: changedData.version });
    store.updateClaim(claim.id, '修改判断文字', claim.version);
    expect(store.getClaim(claim.id).evidence[0]).toEqual(claim.evidence[0]);
    const supplemented = store.supplementClaimEvidence(claim.id);
    expect(supplemented.evidence).toHaveLength(2);
    expect(supplemented.evidence[0]).toEqual(claim.evidence[0]);
    expect(supplemented.evidence[1].content).toContain('后来的数据');
  });
});
