/**
 * Test-only image fixtures. These are real, fully decodable 16×16 PNG/JPEG/WebP
 * images (binary content, no sensitive data). Corrupt fixtures in the tests are
 * produced by truncating or damaging these bytes, never by declaring garbage to
 * be a valid image.
 */
export const REAL_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAACXBIWXMAAAPoAAAD6AG1e1JrAAABtUlEQVQokQXBMQEAIAgEQBoYwfU3IhiBCEYwghGIYAQjsP5mBCJQwTuBCJugC1UwhCaYwiXYQhcc4RWE8AlSWCKUhtbYG7RxNFjjbFiNu8EbT8NtjIbXmA3VBNLZOnqndoxO65idq2N3esfpvB3R+Tqys7pQFE3ZFaocClNOxVJuhSuP4ipD8ZSpKBXIYBvogzowBm1gDq6BPegDZ/AOxOAbyMEaQjE0YzeocRjMOA3LuA1uPIZrDMMzpqFMIJNtok/qxJi0iTm5JvakT5zJOxGTbyInawploS32BV0cC7Y4F9biXvDFs3AXY+Et5kItgWy2jb6pG2PTNubm2tibvnE270Zsvo3crC0UR3N2hzqHw5zTsZzb4c7juM5wPGc6ygVy2A76oR6MQzuYh+tgH/rBObwHcfgO8rCOUC7aZb/Qy3Fhl/NiXe4LvzwX9zIu3mVe1BVIsAV6UAMjaIEZXIEd9MAJ3kAEXyCDFUJ5aI/9QR/Hgz3Oh/W4H/zxPNzHeHiP+VBPIMmW6ElNjKQlZnIldtITJ3kTkXyJTFYKpdCKvaDFUbDiLKziLnjxFG4xCq+YhaoPiXFmMCvBcBwAAAAASUVORK5CYII=";
export const REAL_JPEG_BASE64 =
  "/9j/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAAQABADASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACP/EAB0QAAIABwEAAAAAAAAAAAAAABESBQcTISRCYpL/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAGhEAAgIDAAAAAAAAAAAAAAAAAAYEMgchIv/aAAwDAQACEQMRAD8AOEqoclGyqOQPICchNEx2TKqHJRsqjkDyAnITRMcuyqhyUbIo5UeQE5CaJjsiVMOSjZFHKjyAnITRMccMbW4F9mX2f//Z";
export const REAL_WEBP_BASE64 =
  "UklGRqgAAABXRUJQVlA4IJwAAACQBQCdASoQABAAAMASJbACdLoB+AFKA1wA5AFcC8/4qD8lfwDo//MA/gH4Afv///yU8YizwAD+/0AHmc1GaU7Ubjk6kDt80WICWP3hyjEBcLAFsnYGNFRmdEztT6x8k/GF1wAZ2csbYwbhaMBX0+PM5ne2IbTdaAVR0KC4cT+qFV0/Fx/lr8aqCWpllc//6jTDChpF4ctnzj2CAAA=";

export function realImageFixtures() {
  return {
    PNG: Buffer.from(REAL_PNG_BASE64, "base64"),
    JPEG: Buffer.from(REAL_JPEG_BASE64, "base64"),
    WEBP: Buffer.from(REAL_WEBP_BASE64, "base64"),
  };
}
