/**
 * Builds the single-source agent knowledge bundle from docs/agent/manifest.json
 * into a generated TypeScript module shipped with the server. Run with `--check`
 * to verify the artifact without rewriting it. Locates the repo through
 * import.meta.url so it does not depend on the caller's cwd.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildAgentKnowledgeBundle,
  type AgentKnowledgeManifest,
} from "../packages/core/src/agent-knowledge";
import { operations } from "../packages/core/src/operations";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const args = process.argv.slice(2);
const check = args.includes("--check");
function option(name: string, fallback: string): string {
  const flag = args.find((arg) => arg.startsWith(`--${name}=`));
  return flag ? flag.slice(name.length + 3) : fallback;
}
const docsDir = path.resolve(
  repoRoot,
  option("docs", "docs/agent"),
);
const manifestPath = path.resolve(
  repoRoot,
  option("manifest", path.join("docs/agent", "manifest.json")),
);
const outPath = path.resolve(
  repoRoot,
  option("out", "apps/server/src/generated/agent-knowledge.ts"),
);

function realInside(base: string, target: string) {
  const realBase = fs.realpathSync(base);
  const realTarget = fs.realpathSync(target);
  return realTarget === realBase || realTarget.startsWith(realBase + path.sep);
}

function main() {
  const manifest = JSON.parse(
    fs.readFileSync(manifestPath, "utf8"),
  ) as AgentKnowledgeManifest;
  const contents = new Map<string, string>();
  for (const entry of manifest.content) {
    const file = path.join(docsDir, entry.path);
    if (!fs.existsSync(file)) throw new Error(`缺少内容文件：${entry.path}`);
    if (!fs.statSync(file).isFile())
      throw new Error(`内容不是普通文件：${entry.path}`);
    if (!realInside(docsDir, file))
      throw new Error(`内容路径越界或符号链接逃逸：${entry.path}`);
    contents.set(entry.id, fs.readFileSync(file, "utf8"));
  }
  const bundle = buildAgentKnowledgeBundle({
    manifest,
    contents,
    operationNames: operations.map((operation) => operation.name),
    resolveLink: (fromId, target) => {
      const from = manifest.content.find((entry) => entry.id === fromId);
      const fromDir = from
        ? path.dirname(path.join(docsDir, from.path))
        : docsDir;
      const candidates = [
        path.resolve(fromDir, target),
        path.resolve(repoRoot, target),
      ];
      return candidates.some(
        (candidate) => fs.existsSync(candidate) && fs.statSync(candidate).isFile(),
      );
    },
  });
  const source =
    "/* Generated by scripts/build-agent-knowledge.ts. Do not edit by hand. */\n" +
    'import type { AgentKnowledgeBundle } from "@workbench/core";\n\n' +
    `export const agentKnowledge: AgentKnowledgeBundle = ${JSON.stringify(bundle, null, 2)};\n`;

  if (check) {
    if (!fs.existsSync(outPath)) {
      console.error(`缺少生成产物：${path.relative(repoRoot, outPath)}`);
      process.exit(1);
    }
    const existing = fs.readFileSync(outPath, "utf8");
    if (existing !== source) {
      console.error("生成产物与知识内容不一致，请重新运行生成器。");
      process.exit(1);
    }
    console.log(
      `知识 bundle 校验通过：${bundle.content.length} 项，bundleHash ${bundle.bundleHash}`,
    );
    return;
  }
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, source);
  console.log(
    `已生成知识 bundle：${bundle.content.length} 项，bundleHash ${bundle.bundleHash}`,
  );
}

main();
